// <auto-generated />
using DAL.EfCode;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(NotissimusContext))]
    partial class NotissimusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.EfClasses.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Storages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "The Great Dictator"
                        },
                        new
                        {
                            Id = 2,
                            Text = "Cinema Paradiso"
                        },
                        new
                        {
                            Id = 3,
                            Text = "The Lives of Others"
                        },
                        new
                        {
                            Id = 4,
                            Text = "Grave of the Fireflies"
                        },
                        new
                        {
                            Id = 5,
                            Text = "Paths of Glory"
                        },
                        new
                        {
                            Id = 6,
                            Text = "Django Unchained"
                        },
                        new
                        {
                            Id = 7,
                            Text = "The Shining"
                        },
                        new
                        {
                            Id = 8,
                            Text = "WALL·E"
                        },
                        new
                        {
                            Id = 9,
                            Text = "American Beauty"
                        },
                        new
                        {
                            Id = 10,
                            Text = "The Dark Knight Rises"
                        },
                        new
                        {
                            Id = 11,
                            Text = "Princess Mononoke"
                        },
                        new
                        {
                            Id = 12,
                            Text = "Aliens"
                        },
                        new
                        {
                            Id = 13,
                            Text = "Oldboy"
                        },
                        new
                        {
                            Id = 14,
                            Text = "Once Upon a Time in America"
                        },
                        new
                        {
                            Id = 15,
                            Text = "Witness for the Prosecution"
                        },
                        new
                        {
                            Id = 16,
                            Text = "Das Boot"
                        },
                        new
                        {
                            Id = 17,
                            Text = "Citizen Kane"
                        },
                        new
                        {
                            Id = 18,
                            Text = "North by Northwest"
                        },
                        new
                        {
                            Id = 19,
                            Text = "Vertigo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
